import {
  pgTable,
  text,
  integer,
  timestamp,
  boolean,
  serial,
  varchar,
  numeric,
  index
} from 'drizzle-orm/pg-core';

// =====================================================================
// Auth schema from better-auth
// =====================================================================

// Custom Fields are fields not generated by Better Auth but are added by us to the schema

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified")
    .$defaultFn(() => false)
    .notNull(),
  image: text("image"), // R2 file key, stored in storage table but no FK to avoid circular reference 
  createdAt: timestamp("created_at")
    .$defaultFn(() => /* @__PURE__ */ new Date())
    .notNull(),
  updatedAt: timestamp("updated_at")
    .$defaultFn(() => /* @__PURE__ */ new Date())
    .notNull(),
    role: text("role"),
    banned: boolean("banned"), // From Better-Auth Plugin: Admin
    banReason: text("ban_reason"), // From Better-Auth Plugin: Admin
    banExpires: timestamp("ban_expires"), // From Better-Auth Plugin: Admin
  stripeCustomerId: text("stripe_customer_id"), // From Better-Auth Plugin: Stripe
  isOfficial: boolean("is_official").$defaultFn(() => false), // Custom field for Official linkBD team member badge
  description: text("description"), // Custom field for user bio/about section
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
    impersonatedBy: text("impersonated_by"), // From Better-Auth Plugin: Admin
  activeOrganizationId: text("active_organization_id")
    .references(() => organization.id, { onDelete: "cascade" }), // From Better-Auth Plugin: Organization
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").$defaultFn(
    () => /* @__PURE__ */ new Date(),
  ),
  updatedAt: timestamp("updated_at").$defaultFn(
    () => /* @__PURE__ */ new Date(),
  ),
});

// From Better-Auth Plugin: Organization
export const organization = pgTable("organization", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  slug: text("slug").unique(),
  logo: text("logo"), // Unused
  imageKey: text("image_key"), // Custom field for organization image
  description: text("description"), // Custom field for organization description
  createdAt: timestamp("created_at").notNull(),
  metadata: text("metadata"),
  stripeCustomerId: text("stripe_customer_id").unique(), // Custom field for organization stripe customer id (unused for now)
  isOfficial: boolean("is_official").$defaultFn(() => false), // Custom field for Official linkBD Account badge
  isFeatured: boolean('is_featured').notNull().default(false), // Custom field for featured Businesses
  featuredAt: timestamp('featured_at', { withTimezone: true }), // Custom field for featured Businesses
}, (table) => ({
  featuredAtIdx: index('idx_organizations_featured_at') // Custom index for featured Businesses
    .on(table.isFeatured, table.featuredAt.desc()),
}));

// From Better-Auth Plugin: Organization
export const member = pgTable("member", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  role: text("role").default("member").notNull(),
  createdAt: timestamp("created_at").notNull(),
});

// From Better-Auth Plugin: Organization
export const invitation = pgTable("invitation", {
  id: text("id").primaryKey(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id, { onDelete: "cascade" }),
  email: text("email").notNull(),
  role: text("role"),
  status: text("status").default("pending").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  inviterId: text("inviter_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

// Join table for subscriptions and users/organizations, which is referenced by the referenceId
// From Better-Auth Plugin: Stripe
export const subscription = pgTable("subscription", {
  id: text("id").primaryKey(),
  plan: text("plan").notNull(),
  referenceId: text("reference_id").notNull(), // user.id or organization.id
  stripeCustomerId: text("stripe_customer_id"),
  stripeSubscriptionId: text("stripe_subscription_id"),
  status: text("status").default("incomplete"),
  periodStart: timestamp("period_start"),
  periodEnd: timestamp("period_end"),
  cancelAtPeriodEnd: boolean("cancel_at_period_end"),
  seats: integer("seats"),
});


// =====================================================================
// Main Application Schema Tables
// =====================================================================

// Posts table - social posts for the community
export const posts = pgTable('posts', {
  id: text('id').primaryKey(),
  userId: text('user_id')
    .references(() => user.id, { onDelete: 'cascade' }),
  organizationId: text('organization_id')
    .references(() => organization.id, { onDelete: 'cascade' }),
  content: text('content').notNull(),
  imageKey: text('image_key'), // R2 file key, stored in storage table
  likesCount: integer('likes_count').notNull().default(0),
  visibility: text('visibility').notNull().default('public'),
  createdBy: text('created_by')
    .references(() => user.id, { onDelete: 'set null' }),
  createdAt: timestamp('created_at')
    .defaultNow()
    .notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .notNull(),
}, (table) => ({
  userIdIdx: index('idx_posts_user_id').on(table.userId),
  organizationIdIdx: index('idx_posts_organization_id').on(table.organizationId),
  createdByIdx: index('idx_posts_created_by').on(table.createdBy),
  createdAtIdx: index('idx_posts_created_at').on(table.createdAt),
  visibilityIdx: index('idx_posts_visibility').on(table.visibility),
  
  // Pagination performance indexes
  visibilityCreatedAtIdx: index('idx_posts_visibility_created_at')
    .on(table.visibility, table.createdAt.desc()),
  userVisibilityCreatedAtIdx: index('idx_posts_user_visibility_created_at')
    .on(table.userId, table.visibility, table.createdAt.desc()),
  orgVisibilityCreatedAtIdx: index('idx_posts_org_visibility_created_at')
    .on(table.organizationId, table.visibility, table.createdAt.desc()),
  likesCountCreatedAtIdx: index('idx_posts_likes_count_created_at')
    .on(table.likesCount.desc(), table.createdAt.desc()),
    
  // Daily posting limit performance indexes
  userCreatedAtIdx: index('idx_posts_user_created_at')
    .on(table.userId, table.createdAt.desc()),
  orgCreatedAtIdx: index('idx_posts_org_created_at')
    .on(table.organizationId, table.createdAt.desc()),
}));

// Likes table - track who liked what post
export const likes = pgTable('likes', {
  id: text('id').primaryKey(),
  postId: text('post_id')
    .notNull()
    .references(() => posts.id, { onDelete: 'cascade' }),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at')
    .defaultNow()
    .notNull(),
}, (table) => ({
  postUserIdx: index('idx_likes_post_user').on(table.postId, table.userId),
  userIdIdx: index('idx_likes_user_id').on(table.userId),
}));

export const storage = pgTable('storage', {
  id: text('id').primaryKey(),
  fileKey: text('file_key').notNull().unique(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  organizationId: text('organization_id').references(() => organization.id, { onDelete: 'cascade' }),
  filename: text('filename').notNull(),
  mimeType: text('mime_type').notNull(),
  size: integer('size').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (table) => ({
  userIdIdx: index('idx_storage_user_id').on(table.userId),
  organizationIdIdx: index('idx_storage_organization_id').on(table.organizationId),
  createdAtIdx: index('idx_storage_created_at').on(table.createdAt),
}));

// =====================================================================
// Admin Schema Tables
// =====================================================================

export const migrationRuns = pgTable('migration_runs', {
  id: text('id').primaryKey(),
  migrationFile: text('migration_file').notNull(),
  status: text('status').notNull(), // 'running', 'completed', 'failed', 'rolled_back'
  startedAt: timestamp('started_at').notNull(),
  completedAt: timestamp('completed_at'),
  error: text('error'),
  runBy: text('run_by').references(() => user.id),
});

// =====================================================================
// TypeScript type exports
// =====================================================================

// Auth types
export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;
export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;
export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;
export type Organization = typeof organization.$inferSelect;
export type NewOrganization = typeof organization.$inferInsert;
export type Member = typeof member.$inferSelect;
export type NewMember = typeof member.$inferInsert;
export type Invitation = typeof invitation.$inferSelect;
export type NewInvitation = typeof invitation.$inferInsert;

// Post types
export type Post = typeof posts.$inferSelect;
export type NewPost = typeof posts.$inferInsert;
export type Like = typeof likes.$inferSelect;
export type NewLike = typeof likes.$inferInsert;